---
title: "Problem Set 6"
author: "Barboza-Salern0"
date: "April 3, 2024"
---

# Latent Class Analysis
This problem set asks you to replicate an analysis based on a [workshop on Latent Class Analysis (LCA)](https://pop.princeton.edu/events/2020/latent-class-analysis-using-r) provided by Princeton University. The powerpoint slides are located [here](https://pop.princeton.edu/document/5136), the R script is [here](https://pop.princeton.edu/sites/g/files/toruqf496/files/documents/2020Jan_LatentClassAnalysisPratt_LCA_0.zip) and the data file is [here](https://pop.princeton.edu/sites/g/files/toruqf496/files/documents/2020Jan_LatentClassAnalysisPratt_samhsa_2015F_0.zip).

# Class Notes
The lecture notes are [here](../slides/phhbhp7534_SEM.pdf). The jamovi file that includes my annotated notes from our LCA of greek elections is located [here](../slides/ESS4GR_short_LCA_example.omv) and the table I created of the output to help you is [here](../slides/greek_elections.pdf)

# Procedure

Unzip the files above and get an understanding of the dataset. The data contains information about mental health facilities in 50 states and can be accessed [here](https://www.datafiles.samhsa.gov/study-series/national-mental-health-services-survey-n-mhss-nid13521). The workshop powerpoint has more information about the survey. The steps are simple:

1. Run five latent class models starting with 1 class and ending with 5 classes
2. Select the best fitting model based on the model fit statistics (AIC, BIC, etc.)
3. Include a covariate `payasst` and examine how the likelihood of being in each class conditional on the covariate.

# Software

If you are a PhD student you are encouraged to run this using R. You can simply replicate the code in the workshop and make sure you understand how to analyse the results. As you can see from the horrendous graphical output, it is much nicer and easier to run the analyses using jamovi. jamovi will also allow you to copy and paste the tables for the model fit and the graphs describing the final model.

# Turn in

1. A table of model fit that includes a description of the class you chose and why
2. A brief summary of the classes
3. How the odds of being in the omitted class change given the covariate in the model.

# Starting you out

The variables used in the structural model for the LCA:

- MHINTAKE: Facility offers mental health intake (Q.A1)
- MHDIAGEVAL: Facility offers mental health diagnostic evaluation (Q.A1)
- MHREFERRAL: Facility offers mental health information and/or referral (Q.A1)
- TREATMT: Facility offers substance use treatment (Q.A1)
- ADMINSERV: Facility offers administrative or operational services for mental health treatment facilities (Q.A1)

The covariate is:

- PAYASST: Facility offers treatment at no charge or minimal payment to clients who cannot afford to pay

`samhsa2015 <- read.table(file="samhsa_2015F.csv", header=T, as.is=T, sep=",")`


