project:
  type: website
  render:
    - "*.qmd"
    - "!slides/"
  resources:
    - "files/"
    - "projects/"
    - "slides/*.html"
    - "slides/*.pdf"
    - "slides/img/"
    - "slides/libs/"
    - "slides/css/"
    - "slides/*_files/"

# See https://quarto.org/docs/projects/code-execution.html#freeze
execute:
  freeze: auto  # Re-render only when source changes

bibliography: files/bib/references.bib
csl: files/bib/chicago-author-date.csl
description-meta: "develop, read, critique, design, and conduct high-quality scientific research in public health"

website:
  title: "Research Methods in Public Health"
  site-url: "https://bigdataforsocialjustice/phhbhp7534.com"

  favicon: "/files/icon-512.png"

  twitter-card:
    image: "/files/social-image-sp23.png"
    card-style: summary_large_image
    creator: "@bigdataforsocialjustice"
    # site: "@andrewheiss"

  open-graph:
    image: "/files/social-image-sp23.png"
    locale: en_US

  navbar:
    pinned: true
    background: "#EE6A24"
    right:
      - syllabus.qmd
      - schedule.qmd
      - text: "Content"
        file: content/index.qmd
      - text: "Assignments"
        file: assignment/index.qmd
      - text: "Examples"
        file: example/index.qmd
      - text: "Resources"
        file: resource/index.qmd
      - text: "Alerts"
        file: alerts/index.qmd
      - icon: slack
        href: "https://phhbhp7534.slack.com"
        aria-label: Slack
      - icon: cloud-fill
        href: "https://posit.cloud/content/yours?sort=name_asc"
        aria-label: RStudio.cloud

  sidebar:
    - title: "Content"
      style: "docked"
      search: false
      background: dark
      contents:
        - section: "Overview"
          contents:
            - content/index.qmd
        - section: "Course content"
          contents:
            - text: "1: Intro + Overview"
              file: content/01-content.qmd
            - text: "2: Variables + Units of Analysis"
              file: content/02-content.qmd
            - text: "3: Associations + Confounding"
              file: content/03-content.qmd
            - text: "4: Mediation + Moderation"
              file: content/04-content.qmd
            - text: "5: Research Questions and Hypotheses"
              file: content/05-content.qmd
            - text: "6: Theory + Concepts"
              file: content/06-content.qmd
            - text: "7: Validity + Reliability"
              file: content/07-content.qmd
            - text: "8: Measures + Scale Development"
              file: content/08-content.qmd
            - text: "9: Exam I"
              file: content/exam1.qmd
            - text: "10: Sampling"
              file: content/10-content.qmd
            - text: "11: Data Collection + Survey Design"
              file: content/11-content.qmd
            - text: "12: Analytical methods + observation"
              file: content/12-content.qmd
            - text: "13: Analytical methods + experimental"
              file: content/13-content.qmd
            - text: "14: Analytical methods + geospatial"
              file: content/14-content.qmd
            - text: "15: Analytical methods + qualitative"
              file: content/15-content.qmd
            - text: "16: Presentations + Feedback"
              file: content/16-content.qmd
            - text: "17: Presentations + Feedback"
              file: content/17-content.qmd
            - text: "18: Exam II"
              file: content/18-content.qmd
            - text: "19: No Class + Spring Break"
              file: content/19-content.qmd
            - text: "20: No Class + Spring Break"
              file: content/exam2.qmd
            - text: "21: Pre-experimental designs"
              file: content/21-content.qmd
            - text: "22: Quasi-experimental designs"
              file: content/22-content.qmd
            - text: "23: Randomized Controlled Trials"
              file: content/23-content.qmd
            - text: "24: Observational Designs"
              file: content/24-content.qmd
            - text: "25: Recruitment + Retention"
              file: content/25-content.qmd
            - text: "26: Ethics"
              file: content/26-content.qmd
            - text: "27: Reproducible Research"
              file: content/27-content.qmd
            - text: "28: Student Presentations I"
              file: content/28-content.qmd
            - text: "29: Student Presentations II"
              file: content/29-content.qmd
            - text: "30: Exam III"
              file: content/exam3.qmd

    - title: "Assignments"
      contents:
        - section: "Overview"
          contents:
            - assignment/index.qmd
        - section: "Research assignments"
          contents:
            - assignment/question.qmd
            - resource/annotated.qmd
            - assignment/litreview.qmd
            - resource/final.qmd
        - section: "Other projects"
          contents:
            - assignment/weekly-check-in.qmd
        - section: "Problem sets"
          contents:
            - assignment/01-problem-set.qmd
            - assignment/02-problem-set.qmd
            - assignment/03-problem-set.qmd

    - title: "Examples"
      contents:
        - section: "Overview"
          contents:
            - example/index.qmd
        - section: "Example Code"
          contents:
            - example/infant_mortality.qmd
            - example/bias.qmd
            - example/Confounding.qmd
            - example/moderation.qmd
            - example/mediation.qmd


    - title: "Resources"
      contents:
        - section: "Overview"
          contents:
            - resource/index.qmd
            - resource/r.qmd
            - resource/style.qmd
            - resource/data.qmd
            - resource/opensource.qmd
            - resource/citations.qmd
            - resource/elements.qmd
            - resource/zotero.qmd
            - resource/Rgraphics.qmd
            - resource/annotated.qmd
            - resource/variables.qmd
        - section: "Study guides"
          contents:
            - resource/exam1.qmd
            - resource/final.qmd
        - section: "Guides"
          contents:
            - resource/install.qmd
            - resource/markdown.qmd
            - resource/rmarkdown.qmd
            - resource/unzipping.qmd
            - resource/Rgraphics.qmd

  page-footer:
    left: |
      Content {{< fa brands creative-commons >}} {{< var course.copyright_year >}} by [{{< var instructor.name_no_title >}}]({{< var instructor.url >}}) <br>
      All content licensed under a {{< fa brands creative-commons >}}
      {{< fa brands creative-commons-by >}} {{< fa brands creative-commons-nc >}}
      [Creative Commons Attribution-NonCommercial 4.0 International license (CC BY-NC 4.0)](https://creativecommons.org/licenses/by-nc/4.0/)
    right: |
      Made with {{< fa brands r-project >}} and [Quarto](https://quarto.org/)<br>
      [View the source at {{< fa brands github >}} GitHub]({{< var course.github >}})

format:
  html:
    theme:
      - litera
      - html/custom.scss
    toc: true
    highlight-style: monokai
