---
title: "Validity + Reliability"
date: "2024-01-30"
---

```{r slides-videos, echo=FALSE, include=FALSE}
source(here::here("R", "slide-things.R"))
source(here::here("R", "youtube-playlist.R"))

playlist_id <- "PLS6tnpTr39sFVrHdTifzlyS9dsJjhEhsF"

slide_details <- tibble::tribble(
  ~youtube_id,   ~title, ~slide, ~active,
  "S4OmWxc3h3Y", "Lecture Slides", "1", TRUE
 # "DGbLEgL4g6Y", "Drawing lines", "drawing-lines", TRUE,
#  "n-rV1TIoIgw", "Lines, Greek, and regression", "lines-greek-regression", FALSE,
 # "RYKsrTKWCR4", "Null worlds and statistical significance", "significance", FALSE
)
```

## Readings

### Validity + Reliability

- {{< fa book >}} Singleton RA, Straits BC. Chapter 5: Measurement. In Approaches to Social Research, 5th ed. 2010. p. 115-149.
- {{< fa book >}} Johfre, S. S., & Freese, J. (2021). [Reconsidering the Reference Category.](https://journals.sagepub.com/doi/full/10.1177/0081175020982632?casa_token=OUq-SxezeEQAAAAA:fzIin78vnIG63Q6iaKNOakNWIkAF6UFoZ6VUPfHddZozkvmBOOyzLENq7V6ctO0FgIm1jKf0_UZlnEQ) Sociological Methodology, 51(2), 253–269. https://doi.org/10.1177/0081175020982632
### Required Reading for PhD Students (and recommended for others)


## Lecture Notes

The lecture notes for today can be downloaded [here](/slides/day7.pdf)
The intro to R and `tidyverse` lecture is located [here](/slides/day7_R.pdf)

:::{.callout-tip}
**Fun fact**: If you type <kbd>?</kbd> (or <kbd>shift</kbd> + <kbd>/</kbd>) while going through the slides, you can see a list of special slide-specific commands.
:::

### Your tasks to complete today
-   [ ] Complete Problem Set 4


### Your tasks this week to keep you on track

-   [ ] Begin identifying measures to use in your study

### Competencies and Knowledge
- Foundational knowledge: 3, 6
- Competencies: 2, 9
- MPH Specializations: 4, 7
- PhD Specializations: 4

### Student Evaluation Activity for Assessment
- Exam 1
- Proposal 1

