---
title: Elements of a Research Proposal
format:
  html:
    code-tools: true
    code-fold: show
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(fig.width = 6, fig.height = 3.6, fig.align = "center",
                      fig.retina = 3, collapse = TRUE, out.width = "75%")
set.seed(1234)
options("digits" = 2, "width" = 150)
```
# Theoretical Framework 
Theories explains “why” you believe that your variables are related in the ways you specified (i.e., the variables in your hypothesis)
Theories, theoretical frameworks, and lines of inquiry may be differently handled in quantitative and qualitative endeavors. 

- “In quantitative studies, one uses theory deductively and places it toward the beginning of the plan for a study. The objective is to test or verify theory. One thus begins the study advancing a theory, collects data to test it, and reflects on whether the theory was confirmed or disconfirmed by the results in the study. The theory becomes a framework for the entire study, an organizing model for the research questions or hypotheses for the data collection procedure” (Creswell, 1994, pp. 87-88). 

- In qualitative inquiry, the use of theory and of a line of inquiry depends on the nature of the investigation. In studies aiming at “grounded theory,” for example, theory and theoretical tenets emerge from findings. Much qualitative inquiry, however, also aims to test or verify theory, hence in these cases the theoretical framework, as in quantitative efforts, should be identified and discussed early on.

-	You need to use theory that either you uncovered in the review of research or that you’ve learned in a previous course.

# Statement of the problem
This section may be incorporated in your introduction or your purpose section, or it may stand independently (it depends on the field). Some proposals start with the statement of the problem, rather than a more general introduction. Regardless of placement, at some point you need to clearly identify the problem or knowledge gap that your project is responding to. 

This section should: 

- Answer the question: “What is the gap that needs to be filled?” and/or “What is the problem that needs to be solved?” 
- State the problem clearly early in a paragraph. 
- Carefully consider how you are framing the issue

# Purpose of the study

## Purpose/Aims/Rationale/Research Questions 
- Most proposals include a clear statement of the research objectives, including a description of the questions the research seeks to answer or the hypotheses the research advances. This may be included as part of the introduction, or it may be a separate section. Spend significant time brainstorming before and while you draft this section. 

-	Once you begin your research, you may find that your aims change in emphasis or in number. What is essential is that you focus of your research and to identify key concepts you will be studying. 

- A clear statement of purpose will: 
(1) Explain the goals and research objectives of the study (what do you hope to find?). 
(2) Show the original contributions of your study by explaining how your research questions or approach are different from previous research (what will you add to the field of knowledge?). 
(3) Provide a more detailed account of the points summarized in the introduction. 
(4) Include a rationale for the study (why should we study this?). 

Be clear about what your study will not address (this is especially important if you are applying for competitive funding; narrowly focused studies are more likely to be funded). 

In addition, this section may: 

- Describe the research questions and/or hypotheses of the study;
- Include a subsection defining important terms, especially if they will be new to some readers or if you will use them in an unfamiliar way;
- State limitations of the research; and
- Provide a rationale for the particular subjects of the study. 

## Resources

## Review of Literature 

## Research Questions and Hypotheses

- The questions and hypotheses come after the Review of Research because they are (at least in theory) derived from that review

- A research question poses a relationship between two or more variables but phrases the relationship as a question; a hypothesis represents a declarative statement of the relations between two or more variables (Kerlinger, 1979; Krathwohl, 1988). 

- Deciding whether to use questions or hypotheses depends on factors such as the purpose of the study, the nature of the design and methodology, and the audience 

- Hypotheses can be couched in four kinds of statements. 

1. Literary null—a “no difference” form in terms of theoretical constructs. 
- Examples:

(a) “There is no relationship between support services and academic persistence of nontraditional-aged college women.” Or, “There is no difference in school achievement for high and low self-regulated students.” 

(b) “The more that nontraditional-aged women use support services, the more they will persist academically.” Or, “High self-regulated students will achieve more in their classes than low self-regulated students.”

E.	Questions and hypotheses are testable propositions deduced and directly derived from theory (except in grounded theory studies and similar types of qualitative inquiry). This is important.

F.	Make a clear and careful distinction between the dependent and independent variables and be certain they are clear to the reader. Be excruciatingly consistent in your use of terms. If appropriate, use the same pattern of wording and word order in all hypotheses.

## Methodology 

This section is essential to most good research proposals. How you study a problem is often as important as the results you collect. This section includes a description of the general means through which the goals of the study will be achieved: data methods, materials, procedures, tasks, etc.

-	“The methods or procedures section is really the heart of the research proposal. The activities should be described with as much detail as possible, and the continuity between them should be apparent” (Wiersma, 1995, p. 409).

-	Indicate the methodological steps you will take to answer every question or to test every hypothesis illustrated in the Questions/Hypotheses section. 

-	An effective methodology section should:
1. Introduce the overall methodological approach for each problem or question. Is your study qualitative or quantitative? Are you going to take a special approach, such as participatory action research or use case studies? Describe and justify the approach.

2. Indicate how the approach fits the overall research design. Your methods should have a clear connection with your research questions and/or hypotheses. In other words, make sure that your methods will actually answer your questions—The most common error is that “the proposed tests, or methods, or scientific procedures are unsuited to the stated objective.” But, we are less concerned about that at this stage, and in this class.

- Describe the specific methods of data collection you are going to use—e.g. surveys, interviews, questionnaires, observation, archival or traditional library research. This is critical.

- Explain how you intend to analyze and interpret your results. Will you use statistical analysis? You do NOT need to do the analysis or even describe this in great detail. It is enough to mention that you will be doing a statistical analysis on quantitative data (unless you are in my Multivariate stats class)

- Will you use specific theoretical perspectives to help you analyze a text or explain observed behaviors?

- Address potential limitations. Are there any practical limitations that could affect your data collection? How will you attempt to control for potential confounding variables and errors?

- Think about breaking down your methodology into easily digestible subsections.
1. In the social sciences, these sections may include selection of participants, interview process, profiles, interpretive and analytic framework, methods of analysis, etc.
2. Anticipate and pre-empt the audience’s methodological concerns.

- All research is plagued by the presence of confounding variables (the noise that covers up the information you would like to have). Confounding variables should be minimized by various kinds of controls or be estimated and taken into account by randomization processes (Guba, 1961). In the design section, indicate 

1.	the variables you propose to control and how you propose to control them, experimentally or statistically, and 
2.	any potential intervening or confounding variables that are not being studied – these will be threats to internal validity (see sources of error below)
3.	the variables you propose to randomize, and the nature of the randomizing unit (students, grades, schools, etc.) (most of you won’t be doing an experiment FYI). 

- Be aware of possible sources of error to which your design exposes you. You will not produce a perfect, error free design (no one can). However, you should anticipate possible sources of error and attempt to overcome them or take them into account in your analysis. Moreover, you should disclose to the reader the sources you have identified and what efforts you have made to account for them. 

## Sampling

-	The key reason for being concerned with sampling is that of validity—the extent to which the interpretations of the results of the study follow from the study itself and the extent to which results may be generalized to other situations with other people (Shavelson, 1988). 

-	Sampling is critical to external validity—the extent to which findings of a study can be generalized to people or situations other than those observed in the study. To generalize validly the findings from a sample to some defined population requires that the sample has been drawn from that population according to one of several probability sampling plans. By a probability sample is meant that the probability of inclusion in the sample of any element in the population must be given a priori. All probability samples involve the idea of random sampling at some stage (Shavelson, 1988). In experimentation, two distinct steps are involved. Random selection—participants to be included in the sample have been chosen at random from the same population. Define the population and indicate the sampling plan in detail. Random assignment—participants for the sample have been assigned at random to one of the experimental conditions.

-	Another reason for being concerned with sampling is that of internal validity—the extent to which the outcomes of a study result from the variables that were manipulated, measured, or selected rather than from other variables not systematically treated. Without probability sampling, error estimates cannot be constructed (Shavelson, 1988). 

-	Perhaps the key word in sampling is representative. One must ask oneself, “How representative is the sample of the survey population (the group from which the sample is selected) and how representative is the survey population of the target population (the larger group to which we wish to generalize)?” 

-	When a sample is drawn out of convenience (a nonprobability sample), rationale and limitations must be clearly provided. 

- If available, outline the characteristics of the sample (by gender, race/ethnicity, socioeconomic status, or other relevant group membership). 

-	Detail procedures to follow to obtain informed consent and ensure anonymity and/or confidentiality. 

## Instrumentation 

- Outline the instruments you propose to use (surveys, scales, interview protocols, observation grids). If instruments have previously been used, identify previous studies and findings related to reliability and validity. If instruments have not previously been used, outline procedures you will follow to develop and test their reliability and validity. In the latter case, a pilot study is nearly essential. 

- Because selection of instruments in most cases provides the operational definition of constructs, this is a crucial step in the proposal. For example, it is at this step that a literary conception such as “self-efficacy is related to school achievement” becomes “scores on the Mathematics Self-Efficacy Scale are related to Grade Point Average.” Strictly speaking, results of your study will be directly relevant only to the instrumental or operational statements (Guba, 1961). 

- Include an appendix with a copy of the instruments to be used or the interview protocol to be followed. Also include sample items in the description of the instrument. 

-	For a mailed survey, identify steps to be taken in administering and following up the survey to obtain a high response rate. 

## Data Collection 
- Outline the general plan for collecting the data. This may include survey administration procedures, interview or observation procedures. Include an explicit statement covering the field controls to be employed. If appropriate, discuss how you obtained entré. 

-	Provide a general outline of the time schedule you expect to follow

## Data Analysis 

- the statistical test you choose depends on multiple items but most importantly for this class the level of measurement
- here is the minimum of what you should incorporate into your research proposal

| Statistical test | Independent Var |Dependent Var | 
|:---------|:-----:|:------:|
| t-test    | Categorical   |   Interval-Ratio | 
| chi-square     | Categorical  |   Categorical | 
| ANOVA       | Categorical    |    Interval-Ratio |  
| Pearson Correlation       | Interval-Ratio    |    Interval-Ratio |  
| OLS regression       | Interval-Ratio/Categorical    |    Interval-Ratio |
: Summary of statistical tests and levels of measurement

## Recommended readings
